param()
$ErrorActionPreference = "SilentlyContinue"
# DPI-aware FIRST: window coords are then physical pixels, matching the physical UIA coords
# the helper writes into cursor.state. Without this, DWM scales our position by the DPI factor.
$dpiSig = @"
using System; using System.Runtime.InteropServices;
public static class DshDpi { [DllImport("user32.dll")] public static extern bool SetProcessDPIAware(); }
"@
Add-Type -TypeDefinition $dpiSig
[void][DshDpi]::SetProcessDPIAware()
$dir = Join-Path $env:TEMP "dsh-cua"
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
Set-Content -Path (Join-Path $dir "overlay.pid") -Value $PID -Encoding ascii
Add-Type -AssemblyName System.Drawing
$b64 = "dXNpbmcgU3lzdGVtOyB1c2luZyBTeXN0ZW0uRHJhd2luZzsgdXNpbmcgU3lzdGVtLkRyYXdpbmcuRHJhd2luZzJEOyB1c2luZyBTeXN0ZW0uRHJhd2luZy5JbWFnaW5nOyB1c2luZyBTeXN0ZW0uUnVudGltZS5JbnRlcm9wU2VydmljZXM7CnB1YmxpYyBzdGF0aWMgY2xhc3MgRHNoVmNMYXllciB7CiAgW1N0cnVjdExheW91dChMYXlvdXRLaW5kLlNlcXVlbnRpYWwpXSBzdHJ1Y3QgUE9JTlQgeyBwdWJsaWMgaW50IHgseTsgcHVibGljIFBPSU5UKGludCBhLGludCBiKXt4PWE7eT1iO30gfQogIFtTdHJ1Y3RMYXlvdXQoTGF5b3V0S2luZC5TZXF1ZW50aWFsKV0gc3RydWN0IFNJWkUgeyBwdWJsaWMgaW50IGN4LGN5OyBwdWJsaWMgU0laRShpbnQgYSxpbnQgYil7Y3g9YTtjeT1iO30gfQogIFtTdHJ1Y3RMYXlvdXQoTGF5b3V0S2luZC5TZXF1ZW50aWFsKV0gc3RydWN0IEJMRU5ERlVOQ1RJT04geyBwdWJsaWMgYnl0ZSBCbGVuZE9wLEJsZW5kRmxhZ3MsU291cmNlQ29uc3RhbnRBbHBoYSxBbHBoYUZvcm1hdDsgfQogIFtTdHJ1Y3RMYXlvdXQoTGF5b3V0S2luZC5TZXF1ZW50aWFsKV0gc3RydWN0IEJJVE1BUElORk9IRUFERVIgeyBwdWJsaWMgdWludCBiaVNpemU7IHB1YmxpYyBpbnQgYmlXaWR0aCxiaUhlaWdodDsgcHVibGljIHVzaG9ydCBiaVBsYW5lcyxiaUJpdENvdW50OyBwdWJsaWMgdWludCBiaUNvbXByZXNzaW9uLGJpU2l6ZUltYWdlOyBwdWJsaWMgaW50IGJpWFBlbHNQZXJNZXRlcixiaVlQZWxzUGVyTWV0ZXI7IHB1YmxpYyB1aW50IGJpQ2xyVXNlZCxiaUNsckltcG9ydGFudDsgfQogIFtTdHJ1Y3RMYXlvdXQoTGF5b3V0S2luZC5TZXF1ZW50aWFsKV0gc3RydWN0IEJJVE1BUElORk8geyBwdWJsaWMgQklUTUFQSU5GT0hFQURFUiBibWlIZWFkZXI7IHB1YmxpYyB1aW50IGJtaUNvbG9yczsgfQogIFtEbGxJbXBvcnQoInVzZXIzMi5kbGwiLENoYXJTZXQ9Q2hhclNldC5Vbmljb2RlLFNldExhc3RFcnJvcj10cnVlKV0gc3RhdGljIGV4dGVybiBJbnRQdHIgQ3JlYXRlV2luZG93RXhXKHVpbnQgZXgsc3RyaW5nIGNscyxzdHJpbmcgbmFtZSx1aW50IHN0eWxlLGludCB4LGludCB5LGludCBjeCxpbnQgY3ksSW50UHRyIHAsSW50UHRyIG0sSW50UHRyIGluc3QsSW50UHRyIHEpOwogIFtEbGxJbXBvcnQoInVzZXIzMi5kbGwiKV0gc3RhdGljIGV4dGVybiBib29sIFVwZGF0ZUxheWVyZWRXaW5kb3coSW50UHRyIGh3bmQsSW50UHRyIGRjLHJlZiBQT0lOVCBkc3QscmVmIFNJWkUgc2l6ZSxJbnRQdHIgc3JjRGMscmVmIFBPSU5UIHNyYyx1aW50IGtleSxyZWYgQkxFTkRGVU5DVElPTiBibGVuZCx1aW50IGZsYWdzKTsKICBbRGxsSW1wb3J0KCJ1c2VyMzIuZGxsIildIHN0YXRpYyBleHRlcm4gYm9vbCBTaG93V2luZG93KEludFB0ciBoLGludCBjbWQpOwogIFtEbGxJbXBvcnQoInVzZXIzMi5kbGwiKV0gc3RhdGljIGV4dGVybiBJbnRQdHIgR2V0REMoSW50UHRyIGgpOwogIFtEbGxJbXBvcnQoInVzZXIzMi5kbGwiKV0gc3RhdGljIGV4dGVybiBpbnQgUmVsZWFzZURDKEludFB0ciBoLEludFB0ciBkYyk7CiAgW0RsbEltcG9ydCgiZ2RpMzIuZGxsIildIHN0YXRpYyBleHRlcm4gSW50UHRyIENyZWF0ZUNvbXBhdGlibGVEQyhJbnRQdHIgZGMpOwogIFtEbGxJbXBvcnQoImdkaTMyLmRsbCIpXSBzdGF0aWMgZXh0ZXJuIGJvb2wgRGVsZXRlREMoSW50UHRyIGRjKTsKICBbRGxsSW1wb3J0KCJnZGkzMi5kbGwiKV0gc3RhdGljIGV4dGVybiBJbnRQdHIgU2VsZWN0T2JqZWN0KEludFB0ciBkYyxJbnRQdHIgb2JqKTsKICBbRGxsSW1wb3J0KCJnZGkzMi5kbGwiKV0gc3RhdGljIGV4dGVybiBJbnRQdHIgQ3JlYXRlRElCU2VjdGlvbihJbnRQdHIgaGRjLHJlZiBCSVRNQVBJTkZPIHBibWksdWludCB1c2FnZSxvdXQgSW50UHRyIHBwdkJpdHMsSW50UHRyIGhTZWN0aW9uLHVpbnQgb2Zmc2V0KTsKICBbRGxsSW1wb3J0KCJnZGkzMi5kbGwiKV0gc3RhdGljIGV4dGVybiBib29sIERlbGV0ZU9iamVjdChJbnRQdHIgb2JqKTsKICBbRGxsSW1wb3J0KCJrZXJuZWwzMi5kbGwiLENoYXJTZXQ9Q2hhclNldC5Vbmljb2RlKV0gc3RhdGljIGV4dGVybiBJbnRQdHIgR2V0TW9kdWxlSGFuZGxlVyhzdHJpbmcgbSk7CiAgc3RhdGljIEludFB0ciBod25kPUludFB0ci5aZXJvOwogIHN0YXRpYyB2b2lkIENyZWF0ZSgpewogICAgaWYoaHduZCE9SW50UHRyLlplcm8pIHJldHVybjsKICAgIHVpbnQgZXggPSAweDAwMDgwMDAwdSB8IDB4MDAwMDAwMjB1IHwgMHgwMDAwMDA4MHUgfCAweDAwMDAwMDA4dSB8IDB4MDgwMDAwMDB1OwogICAgdWludCBzdCA9IDB4ODAwMDAwMDB1OwogICAgaHduZCA9IENyZWF0ZVdpbmRvd0V4VyhleCwic3RhdGljIiwiIixzdCwwLDAsNDgsNDgsSW50UHRyLlplcm8sSW50UHRyLlplcm8sR2V0TW9kdWxlSGFuZGxlVyhudWxsKSxJbnRQdHIuWmVybyk7CiAgICAvLyBkZWxpYmVyYXRlbHkgTk9UIHNob3duIGhlcmU6IHRoZSB3aW5kb3cgb25seSBiZWNvbWVzIHZpc2libGUgaW4gU2hvdygpLAogICAgLy8gYWZ0ZXIgaXRzIHBlci1waXhlbC1hbHBoYSBjb250ZW50IGlzIHJlYWR5IOKAlCBhIGJhcmUgbGF5ZXJlZCB3aW5kb3cgbXVzdCBuZXZlciBoaXQgdGhlIHNjcmVlbi4KICB9CiAgc3RhdGljIHZvaWQgQmxpdChpbnQgeCxpbnQgeSl7CiAgICBpZihod25kPT1JbnRQdHIuWmVybykgcmV0dXJuOwogICAgaW50IHc9NDgsaD00ODsKICAgIEludFB0ciBzZD1HZXREQyhJbnRQdHIuWmVybyk7CiAgICBCSVRNQVBJTkZPIGJtaT1uZXcgQklUTUFQSU5GTygpOyBibWkuYm1pSGVhZGVyLmJpU2l6ZT0odWludClNYXJzaGFsLlNpemVPZih0eXBlb2YoQklUTUFQSU5GT0hFQURFUikpOyBibWkuYm1pSGVhZGVyLmJpV2lkdGg9dzsgYm1pLmJtaUhlYWRlci5iaUhlaWdodD0taDsgYm1pLmJtaUhlYWRlci5iaVBsYW5lcz0xOyBibWkuYm1pSGVhZGVyLmJpQml0Q291bnQ9MzI7IGJtaS5ibWlIZWFkZXIuYmlDb21wcmVzc2lvbj0wOwogICAgSW50UHRyIGJpdHM7IEludFB0ciBoYm09Q3JlYXRlRElCU2VjdGlvbihzZCxyZWYgYm1pLDAsb3V0IGJpdHMsSW50UHRyLlplcm8sMCk7CiAgICBpZihoYm09PUludFB0ci5aZXJvKXsgUmVsZWFzZURDKEludFB0ci5aZXJvLHNkKTsgcmV0dXJuOyB9CiAgICBCaXRtYXAgYm1wPW5ldyBCaXRtYXAodyxoLHcqNCxQaXhlbEZvcm1hdC5Gb3JtYXQzMmJwcEFyZ2IsYml0cyk7CiAgICB1c2luZyhHcmFwaGljcyBnPUdyYXBoaWNzLkZyb21JbWFnZShibXApKXsKICAgICAgZy5TbW9vdGhpbmdNb2RlPVNtb290aGluZ01vZGUuQW50aUFsaWFzOyBnLkNsZWFyKENvbG9yLlRyYW5zcGFyZW50KTsKICAgICAgdXNpbmcoR3JhcGhpY3NQYXRoIGdwPW5ldyBHcmFwaGljc1BhdGgoKSl7IGdwLkFkZEVsbGlwc2UoMCwwLDQ4LDQ4KTsKICAgICAgICB1c2luZyhQYXRoR3JhZGllbnRCcnVzaCBwZz1uZXcgUGF0aEdyYWRpZW50QnJ1c2goZ3ApKXsgcGcuQ2VudGVyUG9pbnQ9bmV3IFBvaW50RigyNCwyNCk7IHBnLkNlbnRlckNvbG9yPUNvbG9yLkZyb21BcmdiKDEzMCw4MCwxNTAsMjQ1KTsgQ29sb3JbXSBzYz1uZXcgQ29sb3JbZ3AuUG9pbnRDb3VudF07IGZvcihpbnQgaT0wO2k8c2MuTGVuZ3RoO2krKykgc2NbaV09Q29sb3IuRnJvbUFyZ2IoMCw4MCwxNTAsMjQ1KTsgcGcuU3Vycm91bmRDb2xvcnM9c2M7IGcuRmlsbEVsbGlwc2UocGcsMCwwLDQ4LDQ4KTsgfSB9CiAgICAgIFBvaW50RltdIHB0cz1uZXcgUG9pbnRGW117IG5ldyBQb2ludEYoMjQsMjQpLCBuZXcgUG9pbnRGKDI1LDM5KSwgbmV3IFBvaW50RigyOC41ZiwzNS41ZiksIG5ldyBQb2ludEYoMzEsNDIpLCBuZXcgUG9pbnRGKDM0LDQxKSwgbmV3IFBvaW50RigzMSwzNC41ZiksIG5ldyBQb2ludEYoMzYsMzQuNWYpIH07CiAgICAgIHVzaW5nKFNvbGlkQnJ1c2ggYj1uZXcgU29saWRCcnVzaChDb2xvci5XaGl0ZSkpIGcuRmlsbFBvbHlnb24oYixwdHMpOwogICAgICB1c2luZyhQZW4gcD1uZXcgUGVuKENvbG9yLkJsYWNrLDEuNmYpKXsgcC5MaW5lSm9pbj1MaW5lSm9pbi5Sb3VuZDsgcC5TdGFydENhcD1MaW5lQ2FwLlJvdW5kOyBwLkVuZENhcD1MaW5lQ2FwLlJvdW5kOyBnLkRyYXdQb2x5Z29uKHAscHRzKTsgfQogICAgfQogICAgSW50UHRyIG1kPUNyZWF0ZUNvbXBhdGlibGVEQyhzZCk7IEludFB0ciBvbGQ9U2VsZWN0T2JqZWN0KG1kLGhibSk7CiAgICBQT0lOVCBkc3Q9bmV3IFBPSU5UKHgtMjQseS0yNCk7IFNJWkUgc3o9bmV3IFNJWkUodyxoKTsgUE9JTlQgc3JjPW5ldyBQT0lOVCgwLDApOwogICAgQkxFTkRGVU5DVElPTiBiZj1uZXcgQkxFTkRGVU5DVElPTigpOyBiZi5CbGVuZE9wPTA7IGJmLkJsZW5kRmxhZ3M9MDsgYmYuU291cmNlQ29uc3RhbnRBbHBoYT0yNTU7IGJmLkFscGhhRm9ybWF0PTE7CiAgICBVcGRhdGVMYXllcmVkV2luZG93KGh3bmQsc2QscmVmIGRzdCxyZWYgc3osbWQscmVmIHNyYywwLHJlZiBiZiwyKTsKICAgIFNlbGVjdE9iamVjdChtZCxvbGQpOyBEZWxldGVPYmplY3QoaGJtKTsgRGVsZXRlREMobWQpOyBSZWxlYXNlREMoSW50UHRyLlplcm8sc2QpOwogIH0KICBwdWJsaWMgc3RhdGljIHZvaWQgU2hvdyhpbnQgeCxpbnQgeSl7IENyZWF0ZSgpOyBpZihod25kPT1JbnRQdHIuWmVybykgcmV0dXJuOyBCbGl0KHgseSk7IFNob3dXaW5kb3coaHduZCw0KTsgfQogIHB1YmxpYyBzdGF0aWMgdm9pZCBIaWRlKCl7IGlmKGh3bmQhPUludFB0ci5aZXJvKSBTaG93V2luZG93KGh3bmQsMCk7IH0KfQ=="
$csFile = Join-Path $dir "dsh-vc-layer.cs"
[System.IO.File]::WriteAllText($csFile, [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($b64)))
Add-Type -Path $csFile -ReferencedAssemblies ([System.Drawing.Bitmap].Assembly.Location)
$stateFile = Join-Path $dir "cursor.state"
$lastTs = 0.0
$lastSeen = [DateTime]::MinValue
$visible = $false
# The indicator follows each action and auto-hides 3s after the last one, so it
# closes when the assistant turn ends instead of lingering on screen.
while ($true) {
  if (Test-Path $stateFile) {
    try {
      $st = Get-Content -Path $stateFile -Raw -ErrorAction Stop | ConvertFrom-Json
      if ($null -ne $st -and $st.ts -and ([double]$st.ts -ne $lastTs)) {
        $lastTs = [double]$st.ts
        $lastSeen = [DateTime]::Now
        if ($st.show) { [DshVcLayer]::Show([int][double]$st.x, [int][double]$st.y); $visible = $true }
        else { [DshVcLayer]::Hide(); $visible = $false }
      }
    } catch { }
  }
  if ($visible -and (([DateTime]::Now - $lastSeen).TotalMilliseconds -gt 3000)) {
    [DshVcLayer]::Hide()
    $visible = $false
  }
  Start-Sleep -Milliseconds 100
}
